---
- hosts: k1-all
  tasks:
  - import_role:
      name: bootstrap
  - import_role:
      name: docker-cpu
    vars:
      bip: 192.168.115.5/24
      fixed_cidr: 192.168.115.5/24
    #   directlvm_device: /dev/sdb

