- name: Ensure epel-release installation
  yum:
    name: epel-release
    state: present
- name: Install docker dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - yum-utils
  - device-mapper-persistent-data
  - lvm2
- name: Install docker-ce repository
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
- name: Install docker-ce
  yum:
    name: docker-ce
    state: present
- name: Ensure /etc/docker exists
  file:
    path: /etc/docker
    state: directory
- name: Render /etc/docker/daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
- name: Ensure group "docker" exists
  group:
    name: docker
    state: present
- name: "Start docker service"
  systemd:
    name: docker
    state: restarted
    enabled: yes

